Fixed: now updating the database in POST
error
home/janidu/Documents/GitHub/First_dotNET/backend/Endpoints/Gamesendpoints.cs(58,7i8): error CS1061: 'Game' does not contain a definition for 'id' and no accessible extension method 'id' accepting a first argument of type 'Game' could be found (are you missing a using directive or an assembly reference?)

it cant find the id in game.id becose I is capital speling mistake

TO FIND THIS GO TO THE ERROR RED LINE AND PRESS F12
IT SAYS IT CANT FIND REFRENCE THAT MEANS THE NAME IS CONFLICT GO WERE THE NAMES ARE THEN EDIT IT TO MATCH IF RIGHT WHEN GO THERE AGIN AND PRESS F12 IT WILL GO TO THE REFRENECED CLASS