Error :::
/home/janidu/Documents/GitHub/First_dotNET/backend/Endpoints/Gamesendpoints.cs(65,51): error CS1503: Argument 1: cannot convert from 'int' to 'System.Type

setvalue S was simple made it capital
add game. to Find