build failed
   backend   git:(main)  dotnet run
Using launch settings from /home/janidu/Documents/GitHub/First_dotNET/backend/Properties/launchSettings.json...
Building...
/home/janidu/Documents/GitHub/First_dotNET/backend/Program.cs(19,27): error CS0103: The name 'games' does not exist in the current context

The build failed. Fix the build errors and run again.