fixed cant find games
/home/janidu/Documents/GitHub/First_dotNET/backend/Program.cs(19,27): error CS0103: The name 'games' does not exist in the current context

the above list was named list and below i wrote mapGet("games")
so the games can be found becose it was never made what i made was the lists do i change this erorr and replaces the lists with games in line 7